/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      // Semi Design Token 映射
      "semi-color-white": "var(--semi-color-white)",
      "semi-color-black": "var(--semi-color-black)",
      "semi-color-primary": "var(--semi-color-primary)",
      "semi-color-primary-hover": "var(--semi-color-primary-hover)",
      "semi-color-primary-active": "var(--semi-color-primary-active)",
      "semi-color-primary-disabled": "var(--semi-color-primary-disabled)",
      "semi-color-secondary": "var(--semi-color-secondary)",
      "semi-color-secondary-hover": "var(--semi-color-secondary-hover)",
      "semi-color-secondary-active": "var(--semi-color-secondary-active)",
      "semi-color-tertiary": "var(--semi-color-tertiary)",
      "semi-color-tertiary-hover": "var(--semi-color-tertiary-hover)",
      "semi-color-tertiary-active": "var(--semi-color-tertiary-active)",
      "semi-color-default": "var(--semi-color-default)",
      "semi-color-default-hover": "var(--semi-color-default-hover)",
      "semi-color-default-active": "var(--semi-color-default-active)",
      "semi-color-info": "var(--semi-color-info)",
      "semi-color-info-hover": "var(--semi-color-info-hover)",
      "semi-color-info-active": "var(--semi-color-info-active)",
      "semi-color-success": "var(--semi-color-success)",
      "semi-color-success-hover": "var(--semi-color-success-hover)",
      "semi-color-success-active": "var(--semi-color-success-active)",
      "semi-color-danger": "var(--semi-color-danger)",
      "semi-color-danger-hover": "var(--semi-color-danger-hover)",
      "semi-color-danger-active": "var(--semi-color-danger-active)",
      "semi-color-warning": "var(--semi-color-warning)",
      "semi-color-warning-hover": "var(--semi-color-warning-hover)",
      "semi-color-warning-active": "var(--semi-color-warning-active)",
      "semi-color-border": "var(--semi-color-border)",
      "semi-color-bg-0": "var(--semi-color-bg-0)",
      "semi-color-bg-1": "var(--semi-color-bg-1)",
      "semi-color-bg-2": "var(--semi-color-bg-2)",
      "semi-color-bg-3": "var(--semi-color-bg-3)",
      "semi-color-text-0": "var(--semi-color-text-0)",
      "semi-color-text-1": "var(--semi-color-text-1)",
      "semi-color-text-2": "var(--semi-color-text-2)",
      "semi-color-text-3": "var(--semi-color-text-3)",
      "semi-color-fill-0": "var(--semi-color-fill-0)",
      "semi-color-fill-1": "var(--semi-color-fill-1)",
      "semi-color-fill-2": "var(--semi-color-fill-2)",
    },
    extend: {
      borderRadius: {
        "semi-xs": "var(--semi-border-radius-extra-small)",
        "semi-sm": "var(--semi-border-radius-small)",
        "semi-md": "var(--semi-border-radius-medium)",
        "semi-lg": "var(--semi-border-radius-large)",
      }
    },
  },
  plugins: [],
}
